#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MRP_RTSP_Client.Droid.Resource", IsApplication=true)]

namespace MRP_RTSP_Client.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Rssdp.Resource.String.ApplicationName = global::MRP_RTSP_Client.Droid.Resource.String.ApplicationName;
			global::Rssdp.Resource.String.Hello = global::MRP_RTSP_Client.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int action_add = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int action_add_to_list = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int action_delete_from_list = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int action_scan = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int dialogTitle = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int editText = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int lbltransparent = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int listView1 = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int listView2 = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int mainlinearlayout = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int tab1 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int tab2 = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int tabHost = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int tabhostlinearlayout = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int listviewtemplate = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loading_dialog_box = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int tab_indicator = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int user_input_dialog_box = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int vlc_view = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int network_menu = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int rtsp_menu = 2131099650;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int baseline_add_white_48 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int baseline_find_replace_white_48 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int baseline_playlist_play_black_48 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int baseline_router_black_48 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon1 = 2130837509;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int mrp_db = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Hello = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int add = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int scan = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
